# Generated by Django 6.0.4 on 2026-05-04 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('sonarr_id', models.IntegerField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='Average episode runtime in minutes', null=True)),
                ('state', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('TASTING', 'Tasting'), ('COMMITTED', 'Committed'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('tasting_episodes_count', models.IntegerField(default=3, help_text='Number of episodes to download for tasting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(help_text='Title of the show that triggered this recommendation', max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='vibarr.show')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='PlexWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plex_history_id', models.CharField(max_length=100, unique=True)),
                ('show_title', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('watched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vibarr.show')),
            ],
        ),
    ]
