# Generated by Django 6.0.4 on 2026-05-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonarr_root_folder', models.CharField(blank=True, max_length=500, null=True)),
                ('sonarr_quality_profile_id', models.IntegerField(blank=True, null=True)),
                ('last_plex_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Application Configuration',
            },
        ),
    ]
