# Generated by Django 6.0.4 on 2026-05-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0002_appconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='plex_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
