# Generated by Django 6.0.4 on 2026-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0003_appconfig_plex_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='reasoning',
            field=models.TextField(blank=True, help_text='AI generated reasoning for this suggestion', null=True),
        ),
    ]
