# Generated by Django 6.0.4 on 2026-05-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0004_recommendation_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Optional API Key for remote instances', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='ai_api_url',
            field=models.CharField(default='http://localhost:11434/v1/chat/completions', max_length=500),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='ai_model',
            field=models.CharField(default='gemma4:e4b', max_length=100),
        ),
    ]
