# Generated by Django 6.0.4 on 2026-05-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0005_appconfig_ai_api_key_appconfig_ai_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='max_content_rating',
            field=models.CharField(default='TV-14', help_text='Maximum rating to show without warning', max_length=10),
        ),
        migrations.AddField(
            model_name='show',
            name='content_advisory',
            field=models.CharField(blank=True, help_text='Keywords like Violence, Nudity, etc.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='content_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
