# Generated by Django 6.0.4 on 2026-05-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0006_appconfig_max_content_rating_show_content_advisory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='radarr_quality_profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='radarr_root_folder',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plexwatchevent',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Total duration in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='plexwatchevent',
            name='view_offset',
            field=models.IntegerField(blank=True, help_text='Last watch position in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='media_type',
            field=models.CharField(choices=[('SHOW', 'Show'), ('MOVIE', 'Movie')], default='SHOW', max_length=10),
        ),
        migrations.AddField(
            model_name='show',
            name='radarr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
