# Generated by Django 6.0.4 on 2026-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0007_appconfig_radarr_quality_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='ignored_genres',
            field=models.TextField(blank=True, help_text='Comma-separated list of genres to ignore', null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='plex_user_filter',
            field=models.CharField(blank=True, help_text='Only learn from this Plex User ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='vibe_tags',
            field=models.CharField(blank=True, help_text='AI generated vibe tags (comma separated)', max_length=255, null=True),
        ),
    ]
