# Generated by Django 6.0.4 on 2026-05-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0008_appconfig_ignored_genres_appconfig_plex_user_filter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appconfig',
            old_name='last_plex_sync',
            new_name='last_sync',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='bazarr_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='jellyfin_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='jellyfin_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='media_server_type',
            field=models.CharField(choices=[('PLEX', 'Plex'), ('JELLYFIN', 'Jellyfin'), ('BOTH', 'Plex & Jellyfin')], default='PLEX', max_length=10),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='plex_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='prowlarr_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='seerr_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='seerr_url',
            field=models.CharField(blank=True, help_text='Seerr/Overseerr/Jellyseerr URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='plex_user_filter',
            field=models.CharField(blank=True, help_text='Only learn from this User ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='suggested_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='vibarr.show'),
        ),
        migrations.CreateModel(
            name='MediaWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('source_server', models.CharField(choices=[('PLEX', 'Plex'), ('JELLYFIN', 'Jellyfin'), ('BOTH', 'Plex & Jellyfin')], default='PLEX', max_length=10)),
                ('show_title', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('watched_at', models.DateTimeField()),
                ('view_offset', models.IntegerField(blank=True, help_text='Last watch position in milliseconds', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Total duration in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vibarr.show')),
            ],
        ),
        migrations.DeleteModel(
            name='PlexWatchEvent',
        ),
    ]
