# Generated by Django 6.0.4 on 2026-05-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0009_rename_last_plex_sync_appconfig_last_sync_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediawatchevent',
            name='show_title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediawatchevent',
            name='watched_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='show',
            name='media_type',
            field=models.CharField(choices=[('SHOW', 'Show'), ('MOVIE', 'Movie')], db_index=True, default='SHOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='state',
            field=models.CharField(choices=[('SUGGESTED', 'Suggested'), ('TASTING', 'Tasting'), ('COMMITTED', 'Committed'), ('REJECTED', 'Rejected')], db_index=True, default='SUGGESTED', max_length=20),
        ),
    ]
