# Generated by Django 6.0.4 on 2026-05-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0010_alter_mediawatchevent_show_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
