# Generated by Django 6.0.4 on 2026-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0011_show_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='use_ai_recommendations',
            field=models.BooleanField(default=True, help_text='Set to False to use heuristic matching instead of AI LLM'),
        ),
    ]
