# Generated by Django 6.0.4 on 2026-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0012_appconfig_use_ai_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='ignored_libraries',
            field=models.TextField(blank=True, help_text='Comma-separated list of library names to ignore', null=True),
        ),
    ]
