# Generated by Django 6.0.4 on 2026-05-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0013_appconfig_ignored_libraries'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='discord_webhook_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
