# Generated by Django 6.0.4 on 2026-05-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0014_appconfig_discord_webhook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='has_notified_ready',
            field=models.BooleanField(default=False),
        ),
    ]
