# Generated by Django 6.0.4 on 2026-05-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0015_show_has_notified_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='default_tasting_count',
            field=models.IntegerField(default=3, help_text='Default number of episodes for a new show tasting'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tmdb_language',
            field=models.CharField(default='en-US', help_text='ISO-639-1 language code', max_length=5),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tmdb_region',
            field=models.CharField(default='US', help_text='ISO-3166-1 region code for ratings and availability', max_length=2),
        ),
    ]
