# Generated by Django 6.0.4 on 2026-05-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0016_appconfig_default_tasting_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='streaming_providers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
