# Generated by Django 6.0.4 on 2026-05-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0017_show_streaming_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='radarr_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='radarr_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='sonarr_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='sonarr_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tautulli_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tautulli_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tmdb_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
