# Generated by Django 6.0.4 on 2026-05-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0018_appconfig_radarr_api_key_appconfig_radarr_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediawatchevent',
            name='media_type',
            field=models.CharField(choices=[('SHOW', 'Show'), ('MOVIE', 'Movie')], db_index=True, default='SHOW', max_length=10),
        ),
        migrations.AddField(
            model_name='mediawatchevent',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
