# Generated by Django 6.0.4 on 2026-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0019_mediawatchevent_media_type_mediawatchevent_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='auto_universe_discovery',
            field=models.BooleanField(default=False, help_text='Automatically scan for and architect cinematic universes (MCU, Star Wars, etc.) when you commit to a show.'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='ai_api_url',
            field=models.URLField(default='http://localhost:11434/v1/chat/completions'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='use_ai_recommendations',
            field=models.BooleanField(default=True),
        ),
    ]
