# Generated by Django 6.0.4 on 2026-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0020_appconfig_auto_universe_discovery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this key (e.g. 'Discord Bot')", max_length=100)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
