# Generated by Django 6.0.4 on 2026-05-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0021_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='auto_tasting_threshold',
            field=models.FloatField(default=9.5, help_text="AI confidence score (0-10) above which a recommendation is automatically sent to 'Tasting'."),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='blacklisted_genres',
            field=models.CharField(blank=True, default='', help_text="Comma-separated list of genres to ignore (e.g. 'Horror, Reality TV').", max_length=500),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='url_base',
            field=models.CharField(blank=True, default='', help_text="Base URL path for reverse proxies (e.g. '/vibarr').", max_length=100),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='auto_universe_discovery',
            field=models.BooleanField(default=False),
        ),
    ]
