# Generated by Django 6.0.4 on 2026-05-05 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0022_appconfig_auto_tasting_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating_limit', models.CharField(default='NR', help_text='Max content rating allowed (e.g. PG, TV-14)', max_length=10)),
                ('blacklisted_genres', models.CharField(blank=True, default='', max_length=500)),
                ('auto_switch_enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, help_text='When to auto-activate this lens.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='When to deactivate.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appconfig',
            name='active_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vibarr.persona'),
        ),
    ]
