# Generated by Django 6.0.4 on 2026-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0023_persona_appconfig_active_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='rating_limit',
            new_name='max_content_rating',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='key',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='blacklisted_genres',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='blacklisted_genres',
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(db_index=True, default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='ignored_genres',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of genres to ignore'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='ignored_genres',
            field=models.TextField(blank=True, default='', help_text="Comma-separated list of genres to ignore (e.g. 'Horror, Reality TV')"),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='ignored_libraries',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of library names to ignore'),
        ),
    ]
