# Generated by Django 6.0.4 on 2026-05-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0024_rename_rating_limit_persona_max_content_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='bazarr_url',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='prowlarr_url',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='use_seerr',
            field=models.BooleanField(default=False, help_text='Sync recommendations as requests to Overseerr/Jellyseerr'),
        ),
    ]
