# Generated by Django 6.0.4 on 2026-05-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0025_remove_appconfig_bazarr_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='is_syncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='sync_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
