# Generated by Django 6.0.4 on 2026-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0026_appconfig_is_syncing_appconfig_sync_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='ignored_libraries',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='monitored_libraries',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of library names to monitor'),
        ),
    ]
