# Generated by Django 6.0.4 on 2026-05-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0027_remove_appconfig_ignored_libraries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='ai_model',
            field=models.CharField(default='gemma3:4b', max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='state',
            field=models.CharField(choices=[('SUGGESTED', 'Suggested'), ('TASTING', 'Tasting'), ('COMMITTED', 'Committed'), ('REJECTED', 'Rejected'), ('WATCHED', 'Watched')], db_index=True, default='SUGGESTED', max_length=20),
        ),
    ]
