# Generated by Django 6.0.4 on 2026-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0028_alter_appconfig_ai_model_alter_show_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('tmdb_id', 'media_type'), name='unique_tmdb_id_media_type'),
        ),
    ]
