# Generated by Django 6.0.4 on 2026-05-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0029_alter_show_tmdb_id_show_unique_tmdb_id_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Application timezone for logs and display', max_length=50),
        ),
    ]
