# Generated by Django 6.0.4 on 2026-05-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0030_appconfig_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediawatchevent',
            name='show_title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='source_title',
            field=models.TextField(help_text='Title of the show that triggered this recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='vibe_tags',
            field=models.TextField(blank=True, help_text='AI generated vibe tags (comma separated)', null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='content_advisory',
            field=models.TextField(blank=True, help_text='Keywords like Violence, Nudity, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='content_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='state',
            field=models.CharField(choices=[('SUGGESTED', 'Suggested'), ('TASTING', 'Tasting'), ('COMMITTED', 'Committed'), ('REJECTED', 'Rejected'), ('WATCHED', 'Watched')], db_index=True, default='SUGGESTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='streaming_providers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.TextField(),
        ),
    ]
