# Generated by Django 6.0.4 on 2026-05-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0031_alter_mediawatchevent_show_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='discord_webhook_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='jellyfin_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='jellyfin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='plex_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='plex_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='radarr_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='radarr_root_folder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='radarr_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='seerr_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='seerr_url',
            field=models.TextField(blank=True, help_text='Seerr/Overseerr/Jellyseerr URL', null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sonarr_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sonarr_root_folder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sonarr_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sync_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='tautulli_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='tautulli_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='telegram_bot_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='telegram_chat_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='tmdb_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
