# Generated by Django 6.0.4 on 2026-05-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0032_alter_appconfig_discord_webhook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='max_discovered_items',
            field=models.IntegerField(default=50, help_text='Maximum total number of items to keep in the Discovery Feed.'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='max_tasting_items',
            field=models.IntegerField(default=50, help_text='Maximum total number of active tastings allowed at once.'),
        ),
    ]
