# Generated by Django 6.0.4 on 2026-05-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0033_appconfig_max_discovered_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='max_discovered_items',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='max_discovered_movies',
            field=models.IntegerField(default=50, help_text='Maximum movies to keep in the Discovery Feed.'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='max_discovered_shows',
            field=models.IntegerField(default=50, help_text='Maximum shows to keep in the Discovery Feed.'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='movie_influence_on_shows',
            field=models.IntegerField(default=20, help_text='How much movie taste influences show discovery (0-100).'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='show_influence_on_movies',
            field=models.IntegerField(default=20, help_text='How much show taste influences movie discovery (0-100).'),
        ),
    ]
