# Generated by Django 6.0.4 on 2026-05-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0034_remove_appconfig_max_discovered_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='imdb_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
