# Generated by Django 6.0.4 on 2026-05-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0035_show_imdb_id_show_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='tvdb_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tvdb_pin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tvdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
