# Generated by Django 6.0.4 on 2026-05-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0036_appconfig_tvdb_api_key_appconfig_tvdb_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='auto_collection_sync',
            field=models.BooleanField(default=False, help_text='Automatically create collections in Plex/Jellyfin for detected universes.'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='universe_page_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='show',
            name='universe_name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
