# Generated by Django 6.0.4 on 2026-05-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0037_appconfig_auto_collection_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='h_collection_weight',
            field=models.IntegerField(default=60, help_text='Weight for collection matching (0-100)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='h_genre_weight',
            field=models.IntegerField(default=100, help_text='Weight for genre matching (0-100)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='h_keyword_weight',
            field=models.IntegerField(default=70, help_text='Weight for keyword matching (0-100)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='h_popularity_weight',
            field=models.IntegerField(default=30, help_text='Weight for TMDB popularity (0-100)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='h_rating_weight',
            field=models.IntegerField(default=50, help_text='Weight for TMDB/IMDB ratings (0-100)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='h_seerr_weight',
            field=models.IntegerField(default=40, help_text='Weight for Seerr request history (0-100)'),
        ),
    ]
