# Generated by Django 6.0.4 on 2026-05-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0038_appconfig_h_collection_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='auto_purge_inactive',
            field=models.BooleanField(default=False, help_text='Automatically remove tastings with no progress after 14 days.'),
        ),
    ]
