# Generated by Django 6.0.4 on 2026-05-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0039_appconfig_auto_purge_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='tasting_percentage',
            field=models.IntegerField(default=20, help_text='Percentage of first season episodes to taste (rounded up)'),
        ),
        migrations.AddField(
            model_name='show',
            name='first_season_episodes',
            field=models.IntegerField(blank=True, help_text='Episode count of the first season', null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='default_tasting_count',
            field=models.IntegerField(default=3, help_text='Minimum number of episodes for a new show tasting (the floor)'),
        ),
    ]
