# Generated by Django 6.0.4 on 2026-05-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0040_appconfig_tasting_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='auth_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('EXTERNAL', 'External IPs Only'), ('ALWAYS', 'Always')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='auth_password',
            field=models.TextField(blank=True, help_text='Hashed application password.', null=True),
        ),
    ]
