# Generated by Django 6.0.4 on 2026-05-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0041_appconfig_auth_mode_appconfig_auth_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
