# Generated by Django 6.0.4 on 2026-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0042_appconfig_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='enable_auto_tasting',
            field=models.BooleanField(default=True, help_text="Automatically send high-confidence suggestions to the 'Tasting' queue."),
        ),
    ]
