# Generated by Django 6.0.4 on 2026-05-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0043_appconfig_enable_auto_tasting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='enable_auto_tasting',
            field=models.BooleanField(default=False, help_text="Automatically send high-confidence suggestions to the 'Tasting' queue."),
        ),
    ]
