# Generated by Django 6.0.4 on 2026-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0044_alter_appconfig_enable_auto_tasting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='h_seerr_tag_weight',
            field=models.IntegerField(default=80, help_text='Weight for Seerr request tags (0-100)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='trakt_client_id',
            field=models.TextField(blank=True, help_text='Trakt Client ID for API access', null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='trakt_username',
            field=models.CharField(blank=True, help_text='Trakt Username for seeding taste profile', max_length=150, null=True),
        ),
    ]
