# Generated by Django 6.0.4 on 2026-06-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0045_appconfig_h_seerr_tag_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_downloaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
