# Generated by Django 5.1.6 on 2026-06-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0046_show_is_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='show',
            name='universes',
            field=models.ManyToManyField(blank=True, related_name='shows', to='vibarr.universe'),
        ),
        migrations.CreateModel(
            name='UniverseMergeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField(default=5)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_sources', to='vibarr.universe')),
                ('target_universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_targets', to='vibarr.universe')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_universe', 'target_universe'), name='unique_merge_suggestion')],
            },
        ),
    ]
