# Generated by Django 6.0.4 on 2026-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0048_migrate_universe_name_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='ai_thinking',
            field=models.BooleanField(default=False, help_text='Enable thinking/reasoning effort for compatible models (e.g. o1, o3-mini, Claude 3.7).'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='ai_thinking_effort',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Thinking effort for compatible reasoning models.', max_length=20),
        ),
    ]
