# Generated by Django 6.0.4 on 2026-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibarr', '0050_seed_default_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
